spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password:
    driver Class: org.h2.Driver
